name: findgo
description: Find specials, events and discounts in your area

publish_to: 'none'
version: 1.1.1+12

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Env
  flutter_dotenv: ^5.0.2

  # Geo Location
  geolocator: ^8.2.1
  google_maps_flutter: ^2.1.7

  marker_icon: ^0.7.1
  google_maps_cluster_manager: ^3.0.0+1
#  maps_launcher: ^2.0.1

  # Local Storage
  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.3.0
  hive_flutter: ^1.1.0

  # Networking
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+4

  # Notification
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1

  # Routing
  vrouter: ^1.2.1
  uni_links: ^0.5.1
  url_launcher: ^6.1.3

  # Service Locator
  get_it: ^7.2.0

  # State Management
  flutter_riverpod: ^1.0.4
  # UI
  flutter_html: ^2.2.1
  photo_view: ^0.14.0
  pinput: ^1.2.0
#  scroll_bottom_navigation_bar: ^4.0.0

  # Util
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  jwt_decode: ^0.3.1
  intl: ^0.17.0
  share_plus: ^4.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint
  lint: ^1.8.2

# Generators

  # Hive
  #  build_runner: ^2.0.4
  #  hive_generator: ^1.1.0

  # App Icon Generator:  flutter pub run flutter_launcher_icons:main -f flutter_launcher_icons.yaml
  flutter_launcher_icons: ^0.9.3

  # Splash Screen:  flutter pub run flutter_native_splash:create --path=flutter_native_splash.yaml
  flutter_native_splash: ^2.2.3+1

  # Change Package Name: flutter pub run change_app_package_name:main com.new.package.name
#  change_app_package_name: ^1.0.0

dependency_overrides:
  xml: 6.1.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
