name: findgo
description: Find specials, events and discounts in your area

publish_to: 'none'
version: 1.1.1+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Env
  flutter_dotenv: ^5.0.2

  # Geo Location
  geolocator: ^7.6.2
  google_maps_flutter: ^2.0.10
  marker_icon: ^0.7.1
  google_maps_cluster_manager: ^3.0.0+1
#  maps_launcher: ^2.0.1

  # Local Storage
  cached_network_image: ^3.1.0
  flutter_cache_manager: ^3.1.2
  hive_flutter: ^1.1.0

  # Networking
  http: ^0.13.3
  internet_connection_checker: ^0.0.1+2

  # Notification
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.7

  # Routing
  vrouter: ^1.2.0+13
  uni_links: ^0.5.1
  url_launcher: ^6.0.12

  # Service Locator
  get_it: ^7.2.0

  # State Management
  flutter_riverpod: ^0.14.0+3

  # UI
  flutter_html: ^2.1.2
  photo_view: ^0.12.0
  pinput: ^1.2.0
#  scroll_bottom_navigation_bar: ^4.0.0

  # Util
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  jwt_decode: ^0.3.1
  intl: ^0.17.0
  share_plus: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint
  lint: ^1.7.2

# Generators

  # Hive
  #  build_runner: ^2.0.4
  #  hive_generator: ^1.1.0

  # App Icon Generator:  flutter pub run flutter_launcher_icons:main -f flutter_launcher_icons.yaml
  flutter_launcher_icons: ^0.9.2

  # Splash Screen:  flutter pub run flutter_native_splash:create --path=flutter_native_splash.yaml
  flutter_native_splash: ^1.2.4

  # Change Package Name: flutter pub run change_app_package_name:main com.new.package.name
#  change_app_package_name: ^1.0.0

    #dependency_overrides:
  #  wakelock: 0.5.3+3

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
